#!/bin/sh
#
#  ________  ___       __   ___  ________
# |\   ____\|\  \     |\  \|\  \|\   ____\
# \ \  \___|\ \  \    \ \  \ \  \ \  \___|
#  \ \_____  \ \  \  __\ \  \ \  \ \  \  ___
#   \|____|\  \ \  \|\__\_\  \ \  \ \  \|\  \
#     ____\_\  \ \____________\ \__\ \_______\
#    |\_________\|____________|\|__|\|_______|
#    \|_________|

#    It's delicious.
#    Brought to you by the fine folks at Gilt (http://github.com/gilt)

export GILT_ENV=development;
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
FOREVER="$DIR/../node_modules/.bin/forever"
source ~/.nvm/nvm.sh;
nvm use 6;
node "$FOREVER" start -c "node" app.js
node "$FOREVER" logs app.js -f -n 1
# forever start -c "node --harmony --harmony-proxies" app.js
# forever logs app.js -f -n 1
