FROM docker-registry.gilt.com/swig:latest

# set NODE_ENV production so we're not installing devDependencies
ENV NODE_ENV production
ENV GILT_ENV production

# expose the internal port the node app runs on
EXPOSE {{port}}

# add our files, sans node_modules, to the app dir
ADD . /app

RUN swig install

# Fire up the node app as a daemon with forever
# And tail logs to stdout;
# This also allows the docker conatiner to continue running
CMD forever start -c "node --harmony" app.js && forever --fifo logs 0
