#!/bin/sh
#
#  ________  ___       __   ___  ________
# |\   ____\|\  \     |\  \|\  \|\   ____\
# \ \  \___|\ \  \    \ \  \ \  \ \  \___|
#  \ \_____  \ \  \  __\ \  \ \  \ \  \  ___
#   \|____|\  \ \  \|\__\_\  \ \  \ \  \|\  \
#     ____\_\  \ \____________\ \__\ \_______\
#    |\_________\|____________|\|__|\|_______|
#    \|_________|

#    It's delicious.
#    Brought to you by the fine folks at Gilt (http://github.com/gilt)

cwd=$PWD
source ~/.nvm/nvm.sh
nvm use 0.11

# clone the repo if somehow this is being run after an npm install
cd /web
git clone git@github.com:gilt/gilt-swig.git

# link everything we'll need.
cd /web/gilt-swig/swig-cli && npm link

cd /web/gilt-swig/utilities/swig-log && npm link
cd /web/gilt-swig/utilities/swig-util && npm link

cd /web/gilt-swig/tasks/swig-bundle && npm link
cd /web/gilt-swig/tasks/swig-default && npm link
cd /web/gilt-swig/tasks/swig-deploy && npm link
cd /web/gilt-swig/tasks/swig-install && npm link
cd /web/gilt-swig/tasks/swig-lint && npm link
cd /web/gilt-swig/tasks/swig-publish && npm link
cd /web/gilt-swig/tasks/swig-spec && npm link

cd /web/gilt-swig/tools/swig-app && npm link
cd /web/gilt-swig/tools/swig-app-registry && npm link
cd /web/gilt-swig/tools/swig-tunnel && npm link
cd /web/gilt-swig/tools/swig-zk && npm link

# linking to all of the needed modules -> swig-project/node_modules
cd /web/gilt-swig/swig-project
npm link swig-util
npm link swig-log

npm link swig-bundle
npm link swig-default
npm link swig-deploy
npm link swig-install
npm link swig-lint
npm link swig-publish
npm link swig-spec

npm link swig-app
npm link swig-app-registry
npm link swig-tunnel
npm link swig-zk
npm link

# setup the current directory
cd $cwd
sudo npm install gulp -g --loglevel=info
npm link swig-project
swig-init