#!/bin/sh
#
#  ________  ___       __   ___  ________
# |\   ____\|\  \     |\  \|\  \|\   ____\
# \ \  \___|\ \  \    \ \  \ \  \ \  \___|
#  \ \_____  \ \  \  __\ \  \ \  \ \  \  ___
#   \|____|\  \ \  \|\__\_\  \ \  \ \  \|\  \
#     ____\_\  \ \____________\ \__\ \_______\
#    |\_________\|____________|\|__|\|_______|
#    \|_________|

#    It's delicious.
#    Brought to you by the fine folks at Gilt (http://github.com/gilt)

cyan=$(tput setaf 6)
reset=$(tput sgr0)

echo "\n${cyan}${reset}\n"

cwd=$PWD
source ~/.nvm/nvm.sh
nvm install 0.11.13 >/dev/null
nvm use 0.11.13

# clone the repo if somehow this is being run after an npm install
echo "\n→ ${cyan}Cloning gilt-swig (if it doesn't exist). Errors are OK.${reset}\n"
cd /web
git clone git@github.com:gilt/gilt-swig.git

echo "\n→ ${cyan}Clearing npm cache${reset}:\n"
npm cache clear

echo "→ ${cyan}Linking Swig Modules (npm link)${reset}:\n"

# link everything we'll need.
echo "→ ${cyan}swig-cli${reset}:\n"
cd /web/gilt-swig/swig-cli
rm -rf node_modules
npm install
npm link

utils=("swig-log" "swig-log")

for i in "${utils[@]}"
do
  echo "\n→ ${cyan}utilities/$i${reset}:\n"
  cd "/web/gilt-swig/utilities/$i"
  rm -rf node_modules
  npm install
  npm link
done

tasks=("swig-bundle" "swig-default" "swig-deploy" "swig-install" "swig-lint" "swig-publish" "swig-spec")

for i in "${tasks[@]}"
do
  echo "\n→ ${cyan}tasks/$i${reset}:\n"
  cd "/web/gilt-swig/tasks/$i"
  rm -rf node_modules
  npm install
  npm link
done

utils=("swig-app" "swig-app-registry" "swig-tunnel" "swig-zk")

for i in "${tools[@]}"
do
  echo "\n→ ${cyan}tools/$i${reset}:\n"
  cd "/web/gilt-swig/tools/$i"
  rm -rf node_modules
  npm install
  npm link
done

# linking to all of the needed modules -> swig-project/node_modules
echo "\n→ ${cyan}Linking Utilities, Tasks, and Tools to swig-project${reset}:\n"
cd /web/gilt-swig/swig-project
rm -rf node_modules

echo "→ ${cyan}Linking Utilities${reset}:\n"
npm link swig-util
npm link swig-log

echo "\n→ ${cyan}Linking Tasks${reset}:\n"
npm link swig-bundle
npm link swig-default
npm link swig-deploy
npm link swig-install
npm link swig-lint
npm link swig-publish
npm link swig-spec

echo "\n→ ${cyan}Linking Tools${reset}:\n"
npm link swig-app
npm link swig-app-registry
npm link swig-tunnel
npm link swig-zk

echo "\n→ ${cyan}swig-project${reset}:\n"
npm install
npm link

# setup the current directory
cd $cwd
echo "\n→ ${cyan}Installing Global Gulp${reset}:\n"
sudo npm install gulp -g --loglevel=info

echo "\n→ ${cyan}Linking swig-project in $cwd${reset}:\n"
npm link swig-project

echo "\n→ ${cyan}Starting \`swig init\`${reset}:\n"
swig init